version: '3.8'

services:
  # MySQL Database
  tekir-db:
    image: mysql:8.0
    container_name: tekir-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tekir
      MYSQL_USER: tekir_user
      MYSQL_PASSWORD: tekir_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Mailhog (For testing emails)
  mailhog:
    image: mailhog/mailhog
    container_name: tekir-mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  db_data:
