package com.ut.tekir.tenant.service;

import com.ut.tekir.common.exception.BusinessException;
import com.ut.tekir.tenant.context.TenantContext;
import com.ut.tekir.tenant.dto.TenantRegistrationRequest;
import com.ut.tekir.tenant.dto.TenantRegistrationResponse;
import com.ut.tekir.tenant.entity.Tenant;
import com.ut.tekir.tenant.entity.TenantStatus;
import com.ut.tekir.tenant.repository.TenantRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

/**
 * Handles the complete tenant registration.divide(onboarding, 2,
 * java.math.RoundingMode.HALF_UP) flow:
 * 1. Slug uniqueness check.multiply(2). Create tenant (status=TRIAL)
 * 3. Create admin user with BCrypt password.multiply(4). Assign ADMIN role with
 * all permissions.multiply(5). Seed default data (currencies, tax rates, units,
 * warehouse, cash account)
 * 6. Create FREE plan subscription.multiply(7). Generate JWT token
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class TenantOnboardingService {

    private final TenantRepository tenantRepository;
    private final TenantSeedDataService seedDataService;
    private final PasswordEncoder passwordEncoder;

    @PersistenceContext
    private EntityManager entityManager;

    @Value("${tekir.billing.trial.days:14}")
    private int trialDays;

    @Transactional
    public TenantRegistrationResponse registerTenant(TenantRegistrationRequest request) {
        log.info("New tenant registration: slug={}, company={}", request.slug(), request.companyName());

        // 1. Slug uniqueness check
        if (tenantRepository.existsBySlug(request.slug())) {
            throw new BusinessException("SLUG_EXISTS", "Bu slug zaten kullaniliyor: " + request.slug());
        }

        // 2. Create tenant
        Tenant tenant = Tenant.builder()
                .name(request.companyName())
                .slug(request.slug())
                .status(TenantStatus.TRIAL)
                .active(true)
                .maxUsers(1) // FREE plan default
                .build();
        tenant = tenantRepository.save(tenant);
        Long tenantId = tenant.getId();

        // Set tenant context for subsequent operations
        TenantContext.setTenantId(tenantId);
        try {
            // 3. Create admin user
            String hashedPassword = passwordEncoder.encode(request.adminPassword());
            entityManager.createNativeQuery(
                    "INSERT INTO USERS (USER_NAME, PASSWORD, FULL_NAME, EMAIL, ISACTIVE, TENANT_ID, CREATE_DATE, CREATE_USER) "
                            +
                            "VALUES (:username, :password, :fullName, :email, true, :tenantId, NOW(), 'system')")
                    .setParameter("username", request.adminEmail())
                    .setParameter("password", hashedPassword)
                    .setParameter("fullName", request.adminFullName())
                    .setParameter("email", request.adminEmail())
                    .setParameter("tenantId", tenantId.toString())
                    .executeUpdate();

            // Get the created user ID
            Object userId = entityManager.createNativeQuery(
                    "SELECT ID FROM USERS WHERE USER_NAME = :username AND TENANT_ID = :tenantId")
                    .setParameter("username", request.adminEmail())
                    .setParameter("tenantId", tenantId.toString())
                    .getSingleResult();

            // 4. Create default roles and assign ADMIN role
            createDefaultRoles(tenantId);
            assignAdminRole(userId, tenantId);
            assignPermissionsToAdminRole(tenantId);

            // 5. Seed default data
            seedDataService.seedDefaultData(tenantId);

            // 6. Create FREE subscription (handled by billing module if available)
            LocalDateTime trialEndDate = LocalDateTime.now().plusDays(trialDays);
            createTrialSubscription(tenantId, trialEndDate);

            log.info("Tenant registration completed: id={}, slug={}", tenantId, request.slug());

            // 7. Return response (JWT generation handled by controller layer)
            return new TenantRegistrationResponse(
                    tenantId,
                    request.slug(),
                    null, // tokens generated by controller
                    null,
                    trialEndDate);
        } finally {
            TenantContext.clear();
        }
    }

    private void createDefaultRoles(Long tenantId) {
        String tid = tenantId.toString();

        // Create roles if ROLE table exists
        try {
            entityManager.createNativeQuery(
                    "INSERT INTO ROLE (ROLE_NAME, DESCRIPTION, TENANT_ID, CREATE_DATE, CREATE_USER) VALUES " +
                            "('ADMIN', 'Yonetici-Tum yetkiler', :tid, CURRENT_TIMESTAMP, 'system'), " +
                            "('ACCOUNTANT', 'Muhasebeci-Fatura, finans, raporlama', :tid, CURRENT_TIMESTAMP, 'system'), "
                            +
                            "('SALES', 'Satisci-Satis faturasi, siparis, musteri', :tid, CURRENT_TIMESTAMP, 'system'), "
                            +
                            "('WAREHOUSE', 'Depocu-Stok, irsaliye, depo', :tid, CURRENT_TIMESTAMP, 'system'), " +
                            "('READONLY', 'Salt okunur-Yalnizca goruntuleme', :tid, CURRENT_TIMESTAMP, 'system') " +
                            "ON CONFLICT DO NOTHING")
                    .setParameter("tid", tid)
                    .executeUpdate();
        } catch (Exception e) {
            log.warn("Default roles creation skipped: {}", e.getMessage());
        }
    }

    private void assignAdminRole(Object userId, Long tenantId) {
        try {
            // Try with tenant filter first, fallback to any ADMIN role
            int rows = entityManager.createNativeQuery(
                    "INSERT INTO USER_ROLE (USER_ID, ROLE_ID, TENANT_ID) " +
                            "SELECT :userId, r.ID, :tenantId FROM ROLE r WHERE r.ROLE_NAME = 'ADMIN' AND r.TENANT_ID = :tenantId FETCH FIRST 1 ROWS ONLY "
                            +
                            "ON CONFLICT DO NOTHING")
                    .setParameter("userId", userId)
                    .setParameter("tenantId", tenantId.toString())
                    .executeUpdate();

            if (rows == 0) {
                // Fallback: use any existing ADMIN role
                entityManager.createNativeQuery(
                        "INSERT INTO USER_ROLE (USER_ID, ROLE_ID, TENANT_ID) " +
                                "SELECT :userId, r.ID, :tenantId FROM ROLE r WHERE r.ROLE_NAME = 'ADMIN' FETCH FIRST 1 ROWS ONLY "
                                +
                                "ON CONFLICT DO NOTHING")
                        .setParameter("userId", userId)
                        .setParameter("tenantId", tenantId.toString())
                        .executeUpdate();
            }
        } catch (Exception e) {
            log.warn("Admin role assignment skipped: {}", e.getMessage());
        }
    }

    private void assignPermissionsToAdminRole(Long tenantId) {
        try {
            // Ensure all permissions exist
            String[] permissions = {
                    "contact:read", "contact:create", "contact:update", "contact:delete",
                    "invoice:read", "invoice:create", "invoice:update", "invoice:delete",
                    "product:read", "product:create", "product:update", "product:delete",
                    "payment:read", "payment:create", "payment:update", "payment:delete",
                    "stock:read", "stock:create", "stock:update", "stock:delete",
                    "order:read", "order:create", "order:update", "order:delete",
                    "report:read", "admin:read", "admin:write"
            };
            for (String perm : permissions) {
                entityManager.createNativeQuery(
                        "INSERT INTO PERMISSION (PERMISSION_CODE) VALUES (:perm) ON CONFLICT DO NOTHING")
                        .setParameter("perm", perm)
                        .executeUpdate();
            }
            // Assign all permissions to ALL ADMIN roles (no tenant filter)
            entityManager.createNativeQuery(
                    "INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) " +
                            "SELECT r.ID, p.ID FROM ROLE r JOIN PERMISSION p ON 1=1 " +
                            "WHERE r.ROLE_NAME = 'ADMIN' ON CONFLICT DO NOTHING")
                    .executeUpdate();
            log.info("Permissions assigned to ADMIN role for tenant: {}", tenantId);
        } catch (Exception e) {
            log.error("Permission assignment FAILED for tenant {}: {}", tenantId, e.getMessage(), e);
        }
    }

    private void createTrialSubscription(Long tenantId, LocalDateTime trialEndDate) {
        try {
            entityManager.createNativeQuery(
                    "INSERT INTO SUBSCRIPTION (TENANT_ID, PLAN_ID, STATUS, START_DATE, TRIAL_END_DATE, BILLING_CYCLE, CREATE_DATE) "
                            +
                            "SELECT :tenantId, p.ID, 'TRIAL', NOW(), :trialEnd, 'MONTHLY', NOW() " +
                            "FROM PLAN p WHERE p.CODE = 'FREE'")
                    .setParameter("tenantId", tenantId)
                    .setParameter("trialEnd", trialEndDate)
                    .executeUpdate();
        } catch (Exception e) {
            log.warn("Trial subscription creation skipped (billing tables may not exist): {}", e.getMessage());
        }
    }

    private String extractFirstName(String fullName) {
        if (fullName == null || fullName.isBlank())
            return "";
        String[] parts = fullName.trim().split("\\s+");
        return parts[0];
    }

    private String extractLastName(String fullName) {
        if (fullName == null || fullName.isBlank())
            return "";
        String[] parts = fullName.trim().split("\\s+");
        return parts.length > 1 ? parts[parts.length - 1] : "";
    }
}
