-- Add missing DESCRIPTION and MODULE columns to PERMISSION table
ALTER TABLE PERMISSION ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(200);
ALTER TABLE PERMISSION ADD COLUMN IF NOT EXISTS MODULE VARCHAR(50);

-- Add audit + tenant columns to ROLE_PERMISSION (required by AuditBase entity mapping)
ALTER TABLE ROLE_PERMISSION ADD COLUMN IF NOT EXISTS TENANT_ID VARCHAR(255) DEFAULT '1';
ALTER TABLE ROLE_PERMISSION ADD COLUMN IF NOT EXISTS CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ROLE_PERMISSION ADD COLUMN IF NOT EXISTS UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ROLE_PERMISSION ADD COLUMN IF NOT EXISTS CREATE_USER VARCHAR(10) DEFAULT 'system';
ALTER TABLE ROLE_PERMISSION ADD COLUMN IF NOT EXISTS UPDATE_USER VARCHAR(10);
