-- ==========================================================================
-- V2: CONTACT table schema fix + TEKIR_SEQUENCE
-- Handles cases where V1 was applied with the old incomplete schema.
-- Safe to run on fresh databases (ADD COLUMN IF NOT EXISTS).
-- ==========================================================================

-- Fix sequence table: rename hibernate_sequences → TEKIR_SEQUENCE if needed
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'hibernate_sequences')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tekir_sequence') THEN
        ALTER TABLE hibernate_sequences RENAME TO TEKIR_SEQUENCE;
        ALTER TABLE TEKIR_SEQUENCE RENAME COLUMN sequence_name TO NAME;
        ALTER TABLE TEKIR_SEQUENCE RENAME COLUMN sequence_next_hi_value TO NEXT_VALUE;
        UPDATE TEKIR_SEQUENCE SET NAME = 'GENERIC_SEQ' WHERE NAME = 'genericSeq';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS TEKIR_SEQUENCE (
    NAME VARCHAR(255) NOT NULL,
    NEXT_VALUE BIGINT DEFAULT 1,
    PRIMARY KEY (NAME)
);
INSERT INTO TEKIR_SEQUENCE (NAME, NEXT_VALUE) VALUES ('GENERIC_SEQ', 1) ON CONFLICT DO NOTHING;

-- ==========================================================================
-- Fix CONTACT table: add missing columns (IF NOT EXISTS for safety)
-- ==========================================================================
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS MIDNAME VARCHAR(30);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS SURNAME VARCHAR(30);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS OPEN_DATE DATE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS ISACTIVE_PERSONEL BOOLEAN DEFAULT TRUE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS SGK_NUMBER VARCHAR(20);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS BIRTH_DATE DATE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS BLOOD_GROUP VARCHAR(6);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS FATHER_NAME VARCHAR(30);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS gender INTEGER;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS education INTEGER;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS PASSPORT_NUMBER VARCHAR(255);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS MARITAL_STATUS INTEGER;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS SPOUSE_INCOME_STAT INTEGER;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS CHILD_NUMBER INTEGER;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DEPENDENTS INTEGER;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS CCY VARCHAR(3);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS CCYVAL NUMERIC(19,2) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS LCYVAL NUMERIC(19,2) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS HAS_WITHHOLDING BOOLEAN DEFAULT FALSE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS IS_PUBLIC BOOLEAN DEFAULT FALSE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DISCOUNT_PERCENTAGE BOOLEAN DEFAULT TRUE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DISCOUNT_RATE NUMERIC(18,4) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DISCOUNT_CCY VARCHAR(3);
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DISCOUNT_VALUE NUMERIC(10,2) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DISCOUNT_LCYVAL NUMERIC(10,2) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS HAS_DISCOUNT BOOLEAN DEFAULT FALSE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS PAYMENT_PLAN_ID BIGINT;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS CURRENCY_RATE_TYPE INTEGER DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS OWN_COMPANY_ID BIGINT;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS START_WORKING_DATE DATE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS END_WORKING_DATE DATE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS DEBIT_LIMIT NUMERIC(10,2) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS RISK_LIMIT NUMERIC(10,2) DEFAULT 0;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS "SYSTEM" BOOLEAN;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS CONTACT_TYPE BOOLEAN DEFAULT FALSE;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS EINVOICE_ALIAS_LIST TEXT;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS EINVOICE_CHECKED_AT TIMESTAMP;
ALTER TABLE CONTACT ADD COLUMN IF NOT EXISTS GB_ALIAS VARCHAR(255);

-- Fix wrong column names from old V1 (rename if old names exist)
DO $$
BEGIN
    -- ALLINONE → ALL_TYPE
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='allinone')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='all_type') THEN
        ALTER TABLE CONTACT RENAME COLUMN ALLINONE TO ALL_TYPE;
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='all_type') THEN
        ALTER TABLE CONTACT ADD COLUMN ALL_TYPE BOOLEAN DEFAULT FALSE;
    END IF;

    -- IS_ACTIVE → ISACTIVE
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='is_active')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='isactive') THEN
        ALTER TABLE CONTACT RENAME COLUMN IS_ACTIVE TO ISACTIVE;
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='isactive') THEN
        ALTER TABLE CONTACT ADD COLUMN ISACTIVE BOOLEAN DEFAULT TRUE;
    END IF;

    -- EX_CODE1 → EXCODE1
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='ex_code1')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='excode1') THEN
        ALTER TABLE CONTACT RENAME COLUMN EX_CODE1 TO EXCODE1;
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='excode1') THEN
        ALTER TABLE CONTACT ADD COLUMN EXCODE1 VARCHAR(10);
    END IF;

    -- EX_CODE2 → EXCODE2
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='ex_code2')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='excode2') THEN
        ALTER TABLE CONTACT RENAME COLUMN EX_CODE2 TO EXCODE2;
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='excode2') THEN
        ALTER TABLE CONTACT ADD COLUMN EXCODE2 VARCHAR(10);
    END IF;
END $$;

-- Fix TENANT_ID types: BIGINT → VARCHAR(255) for AuditBase entities
DO $$
BEGIN
    -- CONTACT_ADDRESS
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact_address' AND column_name='tenant_id' AND data_type='bigint') THEN
        ALTER TABLE CONTACT_ADDRESS ALTER COLUMN TENANT_ID TYPE VARCHAR(255) USING TENANT_ID::VARCHAR;
        ALTER TABLE CONTACT_ADDRESS ALTER COLUMN TENANT_ID SET DEFAULT '1';
    END IF;
    -- CONTACT_PHONE
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact_phone' AND column_name='tenant_id' AND data_type='bigint') THEN
        ALTER TABLE CONTACT_PHONE ALTER COLUMN TENANT_ID TYPE VARCHAR(255) USING TENANT_ID::VARCHAR;
        ALTER TABLE CONTACT_PHONE ALTER COLUMN TENANT_ID SET DEFAULT '1';
    END IF;
    -- CONTACT_NETWORK
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact_network' AND column_name='tenant_id' AND data_type='bigint') THEN
        ALTER TABLE CONTACT_NETWORK ALTER COLUMN TENANT_ID TYPE VARCHAR(255) USING TENANT_ID::VARCHAR;
        ALTER TABLE CONTACT_NETWORK ALTER COLUMN TENANT_ID SET DEFAULT '1';
    END IF;
    -- INVOICE
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='invoice' AND column_name='tenant_id' AND data_type='bigint') THEN
        ALTER TABLE INVOICE ALTER COLUMN TENANT_ID TYPE VARCHAR(255) USING TENANT_ID::VARCHAR;
        ALTER TABLE INVOICE ALTER COLUMN TENANT_ID SET DEFAULT '1';
    END IF;
    -- CONTACT
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact' AND column_name='tenant_id' AND data_type='bigint') THEN
        ALTER TABLE CONTACT ALTER COLUMN TENANT_ID TYPE VARCHAR(255) USING TENANT_ID::VARCHAR;
        ALTER TABLE CONTACT ALTER COLUMN TENANT_ID SET DEFAULT '1';
    END IF;
END $$;
