-- ==========================================================================
-- Tekir Modern - PostgreSQL Consolidated Migration (V1)
-- Replaces previous MySQL V1-V18 migrations
-- ==========================================================================

-- Table used by JPA mapping for GenerationType.TABLE
CREATE TABLE hibernate_sequences (
    sequence_name VARCHAR(255) NOT NULL,
    sequence_next_hi_value BIGINT,
    PRIMARY KEY (sequence_name)
);

-- Insert initial value for genericSeq used by most entities
INSERT INTO hibernate_sequences (sequence_name, sequence_next_hi_value) VALUES ('genericSeq', 1) ON CONFLICT DO NOTHING;

-- =============================================
-- USERS & ROLES
-- =============================================
CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    FULL_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    ISACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID VARCHAR(255) DEFAULT '1',
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);
CREATE INDEX IDX_USERS_TENANT ON USERS (TENANT_ID);

CREATE TABLE ROLE (
    ID BIGSERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    INFO VARCHAR(200),
    SYSTEM_ROLE BOOLEAN DEFAULT FALSE,
    TENANT_ID VARCHAR(255) DEFAULT '1',
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);
CREATE INDEX IDX_ROLE_TENANT ON ROLE (TENANT_ID);

CREATE TABLE USER_ROLE (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    TENANT_ID VARCHAR(255) DEFAULT '1',
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_UR_TENANT ON USER_ROLE (TENANT_ID);

CREATE TABLE PERMISSION (
    ID BIGSERIAL PRIMARY KEY,
    PERMISSION_CODE VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE ROLE_PERMISSION (
    ID BIGSERIAL PRIMARY KEY,
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID) ON DELETE CASCADE,
    UNIQUE (ROLE_ID, PERMISSION_ID)
);

CREATE TABLE REFRESH_TOKEN (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOKEN VARCHAR(500) NOT NULL,
    EXPIRY_DATE TIMESTAMP NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_REFRESH_TOKEN_TOKEN ON REFRESH_TOKEN(TOKEN);
CREATE INDEX IDX_REFRESH_TOKEN_USER ON REFRESH_TOKEN(USER_ID);

-- =============================================
-- TENANT & BILLING
-- =============================================
CREATE TABLE TENANT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(100) NOT NULL UNIQUE,
    DOMAIN VARCHAR(255),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    SETTINGS TEXT,
    LOGO_URL VARCHAR(500),
    TAX_NUMBER VARCHAR(20),
    TAX_OFFICE VARCHAR(100),
    MAX_USERS INT,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_TENANT_SLUG ON TENANT (SLUG);
CREATE INDEX IDX_TENANT_DOMAIN ON TENANT (DOMAIN);
CREATE INDEX IDX_TENANT_STATUS ON TENANT (STATUS);

CREATE TABLE PLAN (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    MONTHLY_PRICE NUMERIC(10,2),
    YEARLY_PRICE NUMERIC(10,2),
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    MAX_USERS INT DEFAULT 1,
    MAX_STORAGE_MB INT DEFAULT 100,
    FEATURES TEXT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SUBSCRIPTION (
    ID BIGSERIAL PRIMARY KEY,
    TENANT_ID BIGINT NOT NULL,
    PLAN_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    TRIAL_END_DATE TIMESTAMP,
    NEXT_BILLING_DATE TIMESTAMP,
    BILLING_CYCLE VARCHAR(20),
    PAYMENT_METHOD_ID VARCHAR(100),
    CANCEL_AT_PERIOD_END BOOLEAN DEFAULT FALSE,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SUBSCRIPTION_PLAN FOREIGN KEY (PLAN_ID) REFERENCES PLAN(ID)
);
CREATE INDEX IDX_SUBSCRIPTION_TENANT ON SUBSCRIPTION (TENANT_ID);
CREATE INDEX IDX_SUBSCRIPTION_STATUS ON SUBSCRIPTION (STATUS);

-- Default Tenant & Plan data
INSERT INTO TENANT (ID, NAME, SLUG, STATUS, ACTIVE, MAX_USERS, CREATE_DATE) 
VALUES (1, 'Varsayilan Sirket', 'default', 'ACTIVE', TRUE, 999, CURRENT_TIMESTAMP)
ON CONFLICT (SLUG) DO UPDATE SET NAME = EXCLUDED.NAME;

INSERT INTO PLAN (ID, CODE, NAME, DESCRIPTION, MONTHLY_PRICE, YEARLY_PRICE, MAX_USERS, MAX_STORAGE_MB)
VALUES (1, 'FREE', 'Ucretsiz Baslangic', 'Tekir on muhasebe ucretsiz baslangic paketi', 0.00, 0.00, 1, 100)
ON CONFLICT (CODE) DO UPDATE SET NAME = EXCLUDED.NAME;

-- =============================================
-- DEFINITIONS (City, Currency, Tax, Unit, etc)
-- =============================================
CREATE TABLE CITY (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(10),
    NAME VARCHAR(50) NOT NULL,
    WEIGHT INT,
    ADMIN_LEVEL INT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE PROVINCE (
    ID BIGSERIAL PRIMARY KEY,
    CITY_ID BIGINT,
    NAME VARCHAR(50) NOT NULL,
    WEIGHT INT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_PROVINCE_CITY FOREIGN KEY (CITY_ID) REFERENCES CITY(ID)
);

CREATE TABLE CURRENCY (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(3) NOT NULL,
    NAME VARCHAR(50),
    SYMBOL VARCHAR(4),
    IS_BASE BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE CURRENCIES (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(3) NOT NULL,
    NAME VARCHAR(50),
    SYMBOL VARCHAR(4),
    IS_BASE BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE TAX (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(50),
    RATE NUMERIC(10,2) NOT NULL,
    KIND VARCHAR(20) DEFAULT 'VAT',
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE UNIT (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

-- =============================================
-- FINANCE (Accounts, Banks, etc)
-- =============================================
CREATE TABLE ORGANIZATION (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100),
    INFO TEXT,
    PARENT_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_ORG_PARENT FOREIGN KEY (PARENT_ID) REFERENCES ORGANIZATION(ID)
);

CREATE TABLE ORGANIZATION_LEVEL (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100),
    LEVEL_INDEX INT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE ACCOUNT (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    ORGANIZATION_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE BANK (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    WEIGHT INT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE BANK_BRANCH (
    ID BIGSERIAL PRIMARY KEY,
    BANK_ID BIGINT NOT NULL,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    CITY_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    WEIGHT INT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_BRANCH_BANK FOREIGN KEY (BANK_ID) REFERENCES BANK(ID)
);

CREATE TABLE BANK_ACCOUNT (
    ID BIGSERIAL PRIMARY KEY,
    BANK_BRANCH_ID BIGINT NOT NULL,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    IBAN VARCHAR(50),
    ACCOUNT_NO VARCHAR(50),
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    WEIGHT INT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_BACC_BRANCH FOREIGN KEY (BANK_BRANCH_ID) REFERENCES BANK_BRANCH(ID)
);

CREATE TABLE ORGANIZATION_BANK_ACCOUNT (
    BANK_ACCOUNT_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT NOT NULL,
    PRIMARY KEY (BANK_ACCOUNT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_OBA_BACC FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT(ID),
    CONSTRAINT FK_OBA_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID)
);

CREATE TABLE POS (
    ID BIGSERIAL PRIMARY KEY,
    BANK_ACCOUNT_ID BIGINT,
    CODE VARCHAR(20),
    NAME VARCHAR(100),
    MIN_RATES NUMERIC(10,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    WEIGHT INT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

-- =============================================
-- CONTACTS / CRM
-- =============================================
CREATE TABLE CONTACT_CATEGORY (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    WEIGHT INT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE FOUNDATION (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE CONTACT (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    NAME VARCHAR(255),
    COMPANY VARCHAR(255),
    FULLNAME VARCHAR(255),
    REPRESENTATIVE VARCHAR(100),
    TITLE VARCHAR(100),
    INFO TEXT,
    SSN VARCHAR(11),
    TAX_NUMBER VARCHAR(20),
    TAX_OFFICE VARCHAR(100),
    ALLINONE BOOLEAN DEFAULT FALSE,
    CUSTOMER_TYPE BOOLEAN DEFAULT FALSE,
    PROVIDER_TYPE BOOLEAN DEFAULT FALSE,
    AGENT_TYPE BOOLEAN DEFAULT FALSE,
    PERSONNEL_TYPE BOOLEAN DEFAULT FALSE,
    BRANCH_TYPE BOOLEAN DEFAULT FALSE,
    STORE_TYPE BOOLEAN DEFAULT FALSE,
    SAFE_TYPE BOOLEAN DEFAULT FALSE,
    BANK_TYPE BOOLEAN DEFAULT FALSE,
    FOUNDATION_TYPE BOOLEAN DEFAULT FALSE,
    RELATED_TYPE BOOLEAN DEFAULT FALSE,
    EX_CODE1 VARCHAR(20),
    EX_CODE2 VARCHAR(20),
    PERSON BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CONTACT_CATEGORY_ID BIGINT,
    ORGANIZATION_ID BIGINT,
    FOUNDATION_ID BIGINT,
    
    -- CRM & Identity Fields
    CUSTOMER_CODE VARCHAR(50),
    LEGAL_NAME VARCHAR(255),
    DISPLAY_NAME VARCHAR(255),
    ENTITY_TYPE VARCHAR(20) DEFAULT 'CORPORATE',
    MERSIS_NO VARCHAR(16),
    DEFAULT_CURRENCY VARCHAR(3) DEFAULT 'TRY',
    ACCOUNTING_CODE VARCHAR(50),
    PAYMENT_TERM_DAYS INT DEFAULT 30,
    DISCOUNT_RATE_PERCENT NUMERIC(5,2) DEFAULT 0,
    IBAN VARCHAR(34),
    E_INVOICE_REGISTERED BOOLEAN DEFAULT FALSE,
    PK_ALIAS VARCHAR(255),
    INVOICE_SCENARIO VARCHAR(20),
    CREDIT_LIMIT NUMERIC(18,2) DEFAULT 0,
    RISK_BALANCE NUMERIC(18,2) DEFAULT 0,
    ACCOUNT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    BLOCK_REASON VARCHAR(500),
    SECTOR VARCHAR(100),
    CUSTOMER_SEGMENT VARCHAR(50),
    SALES_REPRESENTATIVE VARCHAR(100),
    FIRST_CONTACT_DATE DATE,
    LAST_CONTACT_DATE DATE,
    REFERRAL_SOURCE VARCHAR(100),
    EINVOICE_CHECKED_AT TIMESTAMP,
    EINVOICE_ALIAS_LIST TEXT,
    GB_ALIAS VARCHAR(255),
    
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_CONTACT_CATEGORY FOREIGN KEY (CONTACT_CATEGORY_ID) REFERENCES CONTACT_CATEGORY(ID),
    CONSTRAINT FK_CONTACT_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID),
    CONSTRAINT FK_CONTACT_FOUNDATION FOREIGN KEY (FOUNDATION_ID) REFERENCES FOUNDATION(ID)
);
CREATE INDEX IDX_CONTACT_TENANT ON CONTACT (TENANT_ID);
CREATE INDEX IDX_CONTACT_ENTITY_TYPE ON CONTACT (ENTITY_TYPE);
CREATE INDEX IDX_CONTACT_ACCOUNT_STATUS ON CONTACT (ACCOUNT_STATUS);
CREATE INDEX IDX_CONTACT_SECTOR ON CONTACT (SECTOR);
CREATE INDEX IDX_CONTACT_CUSTOMER_CODE ON CONTACT (CUSTOMER_CODE);

CREATE TABLE CONTACT_ADDRESS (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    INFO TEXT,
    STREET VARCHAR(255),
    ZIP VARCHAR(20),
    PROVINCE_ID BIGINT,
    CITY_ID BIGINT,
    COUNTRY VARCHAR(100),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    IS_DELIVERY BOOLEAN DEFAULT FALSE,
    IS_INVOICE BOOLEAN DEFAULT FALSE,
    IS_SHIPPING BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_CADDRESS_CONTACT FOREIGN KEY (OWNER_ID) REFERENCES CONTACT(ID) ON DELETE CASCADE
);

CREATE TABLE CONTACT_PHONE (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    INFO TEXT,
    CALLING_CODE VARCHAR(10),
    AREA_CODE VARCHAR(10),
    PHONE_NUMBER VARCHAR(20),
    EXTENTION VARCHAR(10),
    COUNTRY_CODE VARCHAR(10),
    PHONE_TYPE VARCHAR(20),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_CPHONE_CONTACT FOREIGN KEY (OWNER_ID) REFERENCES CONTACT(ID) ON DELETE CASCADE
);

CREATE TABLE CONTACT_NETWORK (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    INFO TEXT,
    VALUE VARCHAR(255),
    NETWORK_TYPE VARCHAR(20),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_CNETWORK_CONTACT FOREIGN KEY (OWNER_ID) REFERENCES CONTACT(ID) ON DELETE CASCADE
);

CREATE TABLE CONTACT_BANK_ACCOUNT (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    BANK_NAME VARCHAR(100),
    BRANCH_NAME VARCHAR(100),
    ACCOUNT_NO VARCHAR(50),
    IBAN VARCHAR(50),
    SWIFT_CODE VARCHAR(20),
    CURRENCY VARCHAR(3),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_CBANKACC_CONTACT FOREIGN KEY (OWNER_ID) REFERENCES CONTACT(ID) ON DELETE CASCADE
);

CREATE TABLE CONTACT_OPPORTUNITY (
    ID BIGSERIAL PRIMARY KEY,
    CONTACT_ID BIGINT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    STAGE VARCHAR(30) NOT NULL DEFAULT 'PROSPECT',
    EXPECTED_REVENUE NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    PROBABILITY INT DEFAULT 0,
    EXPECTED_CLOSE_DATE DATE,
    ACTUAL_CLOSE_DATE DATE,
    NOTE TEXT,
    ASSIGNED_TO VARCHAR(100),
    ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID VARCHAR(50),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(10),
    UPDATE_USER VARCHAR(10),
    CONSTRAINT fk_opp_contact FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_OPP_CONTACT ON CONTACT_OPPORTUNITY (CONTACT_ID);
CREATE INDEX IDX_OPP_STAGE ON CONTACT_OPPORTUNITY (STAGE);

CREATE TABLE CONTACT_PERSON_ENTRY (
    ID BIGSERIAL PRIMARY KEY,
    CONTACT_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    JOB_TITLE VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(30),
    MOBILE VARCHAR(30),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    NOTE VARCHAR(500),
    TENANT_ID VARCHAR(50),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(10),
    UPDATE_USER VARCHAR(10),
    CONSTRAINT fk_pe_contact FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_PE_CONTACT ON CONTACT_PERSON_ENTRY (CONTACT_ID);


-- =============================================
-- PRODUCTS & INVENTORY
-- =============================================
CREATE TABLE PRODUCT_CATEGORY (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    WEIGHT INT,
    PARENT_ID BIGINT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_PCAT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    BARCODE1 VARCHAR(50),
    BARCODE2 VARCHAR(50),
    BARCODE3 VARCHAR(50),
    PRODUCT_TYPE VARCHAR(20) DEFAULT 'Product',
    PRODUCT_GROUP VARCHAR(20),
    UNIT VARCHAR(10),
    TAX_RATE NUMERIC(10,2) DEFAULT 0,
    BUY_PRICE NUMERIC(10,2) DEFAULT 0,
    SELL_PRICE NUMERIC(10,2) DEFAULT 0,
    EXPENSE_PRICE NUMERIC(10,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    HAS_VARIANTS BOOLEAN DEFAULT FALSE,
    PRODUCT_CATEGORY_ID BIGINT,
    GROUP_CODE VARCHAR(20),
    IMAGE VARCHAR(500),
    WEIGHT INT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_PRODUCT_CAT FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(ID)
);
CREATE INDEX IDX_PRODUCT_TENANT ON PRODUCT (TENANT_ID);

CREATE TABLE WAREHOUSE (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(100) NOT NULL,
    INFO TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    ORGANIZATION_ID BIGINT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_WAREHOUSE_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID)
);

-- =============================================
-- INVOICING & SHIPMENT
-- =============================================
CREATE TABLE INVOICE (
    ID BIGSERIAL PRIMARY KEY,
    CONTACT_ID BIGINT,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    TXNDATE DATE NOT NULL,
    DOCUMENT_DATE DATE,
    DUE_DATE DATE,
    DOCUMENT_NUMBER VARCHAR(50),
    INFO TEXT,
    REFTXT VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    TOTAL_TAX NUMERIC(18,2) DEFAULT 0,
    TOTAL_FEE NUMERIC(18,2) DEFAULT 0,
    TOTAL_EXPENSE NUMERIC(18,2) DEFAULT 0,
    TOTAL_DISCOUNT NUMERIC(18,2) DEFAULT 0,
    GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    EXCHANGE_RATE NUMERIC(10,6) DEFAULT 1.0,
    CCY_TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_TAX NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_FEE NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_EXPENSE NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_DISCOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    TRADE_ACTION VARCHAR(20) NOT NULL,
    SHIPPING_DATE DATE,
    ACCOUNT_ID BIGINT,
    WAREHOUSE_ID BIGINT,
    PAID_AMOUNT NUMERIC(18,2) DEFAULT 0,
    ADDRESS_SNAPSHOT TEXT,
    EINVOICE_STATUS VARCHAR(20) DEFAULT 'NONE',
    EINVOICE_UUID CHAR(36),
    EINVOICE_SCENARIO VARCHAR(20),
    EINVOICE_TYPE VARCHAR(20),
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_INVOICE_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID),
    CONSTRAINT FK_INVOICE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT FK_INVOICE_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(ID)
);

CREATE TABLE INVOICE_ITEM (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT,
    PRODUCT_NAME VARCHAR(100),
    INFO TEXT,
    QUANTITY NUMERIC(10,2) DEFAULT 0,
    UNIT_PRICE NUMERIC(18,4) DEFAULT 0,
    UNIT VARCHAR(10),
    TAX_RATE NUMERIC(10,2) DEFAULT 0,
    TAX_AMOUNT NUMERIC(18,2) DEFAULT 0,
    DISCOUNT_RATE NUMERIC(10,2) DEFAULT 0,
    DISCOUNT_AMOUNT NUMERIC(18,2) DEFAULT 0,
    TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    EXCHANGE_RATE NUMERIC(10,6) DEFAULT 1.0,
    CCY_UNIT_PRICE NUMERIC(18,4) DEFAULT 0,
    CCY_TAX_AMOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_DISCOUNT_AMOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    IS_EXPENSE BOOLEAN DEFAULT FALSE,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_IITEM_INVOICE FOREIGN KEY (OWNER_ID) REFERENCES INVOICE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_IITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE EINVOICE_SETTINGS (
    ID BIGSERIAL PRIMARY KEY,
    TENANT_ID BIGINT NOT NULL UNIQUE,
    PROVIDER_TYPE VARCHAR(30) NOT NULL DEFAULT 'FORIBA',
    API_URL VARCHAR(500),
    API_KEY VARCHAR(500),
    API_SECRET VARCHAR(500),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(500),
    SENDER_VKN VARCHAR(11),
    SENDER_ALIAS VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    EINVOICE_ENABLED BOOLEAN DEFAULT FALSE,
    EARCHIVE_ENABLED BOOLEAN DEFAULT FALSE,
    EDESPATCH_ENABLED BOOLEAN DEFAULT FALSE,
    EPRODUCER_ENABLED BOOLEAN DEFAULT FALSE,
    ESMM_ENABLED BOOLEAN DEFAULT FALSE,
    UBL_GENERATION_MODE VARCHAR(20) DEFAULT 'PROVIDER_SIDE',
    DEFAULT_TEMPLATE VARCHAR(100),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE EINVOICE_LOG (
    ID BIGSERIAL PRIMARY KEY,
    TENANT_ID BIGINT NOT NULL,
    INVOICE_ID BIGINT,
    DIRECTION VARCHAR(10) NOT NULL DEFAULT 'OUTBOUND',
    DOCUMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'EINVOICE',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    UUID CHAR(36),
    ENVELOPE_ID VARCHAR(50),
    PROVIDER_RESPONSE TEXT,
    ERROR_MESSAGE TEXT,
    SENT_AT TIMESTAMP,
    RECEIVED_AT TIMESTAMP,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_einvoice_log_invoice FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID) ON DELETE SET NULL
);
CREATE INDEX IDX_einvoice_log_invoice ON EINVOICE_LOG(INVOICE_ID);
CREATE INDEX IDX_einvoice_log_tenant ON EINVOICE_LOG(TENANT_ID);
CREATE INDEX IDX_einvoice_log_uuid ON EINVOICE_LOG(UUID);

CREATE TABLE SHIPMENT_NOTE (
    ID BIGSERIAL PRIMARY KEY,
    INVOICE_ID BIGINT,
    CONTACT_ID BIGINT,
    CODE VARCHAR(20) NOT NULL,
    TXN_DATE DATE NOT NULL,
    DOCUMENT_DATE DATE,
    INFO TEXT,
    REFTXT VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    TRADE_ACTION VARCHAR(20) NOT NULL,
    ACCOUNT_ID BIGINT,
    WAREHOUSE_ID BIGINT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_SHIPMENT_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID) ON DELETE SET NULL,
    CONSTRAINT FK_SHIPMENT_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID),
    CONSTRAINT FK_SHIPMENT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT FK_SHIPMENT_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(ID)
);

CREATE TABLE ORDER_NOTE (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    CONTACT_ID BIGINT,
    ACCOUNT_ID BIGINT,
    WAREHOUSE_ID BIGINT,
    TXN_DATE DATE NOT NULL,
    DELIVERY_DATE DATE,
    DOC_NUMBER VARCHAR(50),
    DOC_DATE DATE,
    REFTXT VARCHAR(50),
    INFO TEXT,
    TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    TOTAL_TAX NUMERIC(18,2) DEFAULT 0,
    TOTAL_DISCOUNT NUMERIC(18,2) DEFAULT 0,
    GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    TOTAL_FEE NUMERIC(18,2) DEFAULT 0,
    TOTAL_EXPENSE NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    TRADE_ACTION VARCHAR(20) NOT NULL,
    ORDER_STATUS VARCHAR(20) DEFAULT 'DRAFT',
    SHIPPING_COST NUMERIC(18,2) DEFAULT 0,
    PAYMENT_TERM_DAYS INT DEFAULT 0,
    CCY_TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_TAX NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_DISCOUNT NUMERIC(18,2) DEFAULT 0,
    CCY_GRAND_TOTAL NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_FEE NUMERIC(18,2) DEFAULT 0,
    CCY_TOTAL_EXPENSE NUMERIC(18,2) DEFAULT 0,
    CCY_SHIPPING_COST NUMERIC(18,2) DEFAULT 0,
    CCY_EXCHANGE_RATE NUMERIC(10,6) DEFAULT 1.0,
    BILLING_ADDRESS_SNAPSHOT TEXT,
    SHIPPING_ADDRESS_SNAPSHOT TEXT,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_ORDER_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID),
    CONSTRAINT FK_ORDER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT FK_ORDER_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(ID)
);

-- =============================================
-- PAYMENTS & TRANSACTIONS
-- =============================================
CREATE TABLE PAYMENT (
    ID BIGSERIAL PRIMARY KEY,
    CONTACT_ID BIGINT,
    ACCOUNT_ID BIGINT,
    CODE VARCHAR(20) NOT NULL,
    TXN_DATE DATE NOT NULL,
    INFO TEXT,
    REFTXT VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    ACTION VARCHAR(20) NOT NULL,
    PROCESS_TYPE VARCHAR(20) NOT NULL,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_PAYMENT_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID),
    CONSTRAINT FK_PAYMENT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE PAYMENT_ITEM (
    ID BIGSERIAL PRIMARY KEY,
    PAYMENT_ID BIGINT NOT NULL,
    AMOUNT NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    EXCHANGE_RATE NUMERIC(10,6) DEFAULT 1.0,
    CCY_AMOUNT NUMERIC(18,2) DEFAULT 0,
    INFO TEXT,
    REFTXT VARCHAR(50),
    LINE_TYPE VARCHAR(20) NOT NULL,
    BANK_ACCOUNT_ID BIGINT,
    MATCHED_DOCUMENT_ID BIGINT,
    MATCHED_DOCUMENT_TYPE VARCHAR(20),
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_PITEM_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PITEM_BANKACC FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT(ID)
);

CREATE TABLE CHEQUE (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    INFO TEXT,
    CONTACT_ID BIGINT,
    AMOUNT NUMERIC(18,2) DEFAULT 0,
    ISSUE_DATE DATE,
    DUE_DATE DATE,
    CHEQUE_OWNER VARCHAR(100),
    BANK_NAME VARCHAR(100),
    BANK_BRANCH VARCHAR(100),
    ACCOUNT_NO VARCHAR(50),
    IS_CLIENT_CHEQUE BOOLEAN DEFAULT TRUE,
    DOCUMENT_STATUS VARCHAR(20) DEFAULT 'PORTFOLIO',
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_CHEQUE_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID)
);

CREATE TABLE PROMISSORY_NOTE (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    INFO TEXT,
    CONTACT_ID BIGINT,
    AMOUNT NUMERIC(18,2) DEFAULT 0,
    ISSUE_DATE DATE,
    DUE_DATE DATE,
    PROMISSORY_OWNER VARCHAR(100),
    PAYMENT_PLACE VARCHAR(100),
    IS_CLIENT_NOTE BOOLEAN DEFAULT TRUE,
    DOCUMENT_STATUS VARCHAR(20) DEFAULT 'PORTFOLIO',
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50),
    CONSTRAINT FK_PNOTE_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID)
);

CREATE TABLE BOND (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    INFO TEXT,
    AMOUNT NUMERIC(18,2) DEFAULT 0,
    ISSUE_DATE DATE,
    DUE_DATE DATE,
    DOCUMENT_STATUS VARCHAR(20) DEFAULT 'PORTFOLIO',
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

CREATE TABLE FUND_TRANSFER (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    INFO TEXT,
    TXN_DATE DATE NOT NULL,
    AMOUNT NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'TRY',
    FROM_ACCOUNT_ID BIGINT,
    TO_ACCOUNT_ID BIGINT,
    FROM_BANK_ACCOUNT_ID BIGINT,
    TO_BANK_ACCOUNT_ID BIGINT,
    FROM_CONTACT_ID BIGINT,
    TO_CONTACT_ID BIGINT,
    TRANSFER_TYPE VARCHAR(20) NOT NULL,
    TENANT_ID BIGINT DEFAULT 1,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT 'system',
    UPDATE_USER VARCHAR(50)
);

-- Pre-seed some default permissions
INSERT INTO PERMISSION (PERMISSION_CODE) VALUES 
('contact:read'), ('contact:create'), ('contact:update'), ('contact:delete'),
('invoice:read'), ('invoice:create'), ('invoice:update'), ('invoice:delete'),
('product:read'), ('product:create'), ('product:update'), ('product:delete'),
('payment:read'), ('payment:create'), ('payment:update'), ('payment:delete'),
('stock:read'), ('stock:create'), ('stock:update'), ('stock:delete'),
('order:read'), ('order:create'), ('order:update'), ('order:delete'),
('report:read'), ('admin:read'), ('admin:write');
